import type { Metadata } from "next";
import { Geist, Geist_Mono,League_Spartan,Sofia_Sans_Semi_Condensed } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const leagueSpartano = League_Spartan({
    variable: "--font-league-spartan",
    subsets: ["latin"],
    weight:['400','700','900']

});
const sofiaSansSemiCondensed = Sofia_Sans_Semi_Condensed({
    variable: "--font-sofia-Sans-Semi-Condensed",
    subsets: ["latin"],
    weight:['400','700','900']

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${leagueSpartano.variable} ${sofiaSansSemiCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
